[ORG 0X100]
; THIS CODE WILL DISPLAY THE SCAN CODE OF ANY ( PRESSED BY YOU);
START:
      MOV AH,0
      INT 16H 
      SHR AX,8
   ; MOV AX,0XAB34	;MOV CX,0; CX WILL CONTAIN THE COUNT OF DIGITS IN THE NUMBER PROVIDED
	MOV CX,0
DIGIT:	MOV DX,0
	MOV BX,10
	DIV BX ; 		DX:AX/BX			WORD TYPE DIVISION----> QUOTIENT---->AX  , REMIANDER---> DX
	CMP DX,9
	JBE SKIP
	ADD DX,7
SKIP:
	ADD DX,48
	PUSH DX
	INC CX
	CMP AX,0            ; 4--PUSH->3---PUSH->B--PUSH-->A PUSH
	JNE DIGIT

; PRINTING
	MOV AX,0XB800
	MOV ES,AX
	MOV DI,0
L1:
	POP AX ; ASCII OF CHARACTER/DIGIT
	MOV AH,0X7
	MOV [ES:DI],AX
	ADD DI,2

LOOP L1
JMP START
MOV AX,0X4C00
INT 21H